steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-test', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/cloud-run-test']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'gcr.io/$PROJECT_ID/cloud-run-test', '--region', 'us-central1']
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'container'
#   - 'images'
#   - 'add-tag'
#   - 'gcr.io/$PROJECT_ID/cloud-run-test'
#   - 'latest'